name: Beak

on: [push, pull_request]
  
jobs:
  build-deploy:
    name: Build, Package, and Deploy
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install modules
        run: yarn

      - name: Build and package
        if: github.ref == 'refs/heads/master'
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUILD_NUMBER: ${{ steps.short-sha.outputs.sha }}
        run: yarn package
      - name: Build and package
        if: github.ref != 'refs/heads/master'
        run: yarn build

      - name: Delete stupid folders
        run: |
          rm -rf ./packages/electron-host/dist-electron/.icon-icns
          rm -rf ./packages/electron-host/dist-electron/.icon-ico
          rm -rf ./packages/electron-host/dist-electron/mac
          rm -rf ./packages/electron-host/dist-electron/mac-arm64
          rm -rf ./packages/electron-host/dist-electron/win-unpacked
          rm -rf ./packages/electron-host/dist-electron/win-ia32-unpacked

      - name: Write commit hash
        if: github.ref == 'refs/heads/master'
        run: mkdir current; echo "commits/${{ github.sha }}/" >> ./current/current
      - name: Upload artifacts to S3
        if: github.ref == 'refs/heads/master'
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUILDS_BUCKET }}
          source_dir: 'packages/electron-host/dist-electron/'
          destination_dir: 'commits/${{ github.sha }}/'
      - name: Upload latest build manifest to s3
        if: github.ref == 'refs/heads/master'
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUILDS_BUCKET }}
          source_dir: 'current'
          destination_dir: 'manifest/'
