name: beak-web

on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/beak-web.yml'
      - 'package.json'
      - 'yarn.lock'
      - '/packages/web-*/*'

jobs:
  build-deploy:
    name: build and deploy
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Lint, typecheck, and test
        run: |
          yarn lint
          yarn typecheck
          yarn test

      - name: Build web code
        env:
          BUILD_ENVIRONMENT: ci
          COMMIT_IDENTIFIER: ${{ github.sha }}
          BUILD_NUMBER: ${{ steps.short-sha.outputs.sha }}
          SENTRY_WEBSITE_API_KEY: ${{ secrets.SENTRY_WEBSITE_API_KEY }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: yarn build:web

      - name: Deploy website to production
        if: "startsWith(github.event.head_commit.message, 'release(')"
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './packages/website/public'
          production-branch: master
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_WEBSITE }}
        timeout-minutes: 4

      - name: Deploy share to production
        if: "startsWith(github.event.head_commit.message, 'release(')"
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET_SHARE }}
          source_dir: 'packages/share/dist/'
          destination_dir: ''

      - name: Delete robots/humans/sitemap for nonprod
        run: |
          rm packages/website/public/robots.txt
          rm packages/website/public/humans.txt
          rm packages/website/public/sitemap-0.xml
          rm packages/website/public/sitemap-index.xml

      - name: Deploy website (nonprod)
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './packages/website/public'
          production-branch: master
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_WEBSITE_NONPROD }}
        timeout-minutes: 4

      - name: Deploy share (nonprod)
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET_SHARE_NONPROD }}
          source_dir: 'packages/share/dist/'
          destination_dir: ''
