name: Beak

on: [push, pull_request]
  
jobs:
  build-deploy:
    name: Build, Package, and Deploy
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        # if: steps.yarn-cache.outputs.cache-hit != 'true' # disabled for now-
        run: yarn
      - name: Build and package
        run: yarn package

      - name: Delete app folder
        run: rm -rf ./packages/electron-host/dist-electron/mac

      - name: Write commit hash
        run: mkdir current; echo "${{ github.sha }}" >> ./current/current
      - name: Upload S3
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUILDS_BUCKET }}
          source_dir: 'packages/electron-host/dist-electron/'
          destination_dir: '${{ github.sha }}/'
      - name: Upload current file to S3
        uses: shallwefootball/upload-s3-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUILDS_BUCKET }}
          source_dir: 'current'
          destination_dir: 'manifest/'
